<?php
// Sample game data
$games = [
    [
        'title' => 'The Last Guardian',
        'category' => 'Action-Adventure',
        'release_date' => '2016-12-06',
        'sales_numbers' => '2,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Dark and Darker',
        'category' => 'Stealth Action',
        'release_date' => '2023-04-15',
        'sales_numbers' => '1,500,000',
        'github_username' => 'Doononthon',
    ],
    [
        'title' => 'The Elder Scrolls V: Skyrim',
        'category' => 'RPG',
        'release_date' => '2011-11-11',
        'sales_numbers' => '30,000,000+',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Overwatch',
        'category' => 'First-person shooter',
        'release_date' => '2016-05-24',
        'sales_numbers' => '50,000,000+',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Assassin\'s Creed Valhalla',
        'category' => 'Adventure',
        'release_date' => '2020-11-10',
        'sales_numbers' => '14,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'The Witcher 3: Wild Hunt',
        'category' => 'RPG',
        'release_date' => '2015-05-19',
        'sales_numbers' => '30,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'The Legend of Zelda: Breath of the Wild',
        'category' => 'Action-Adventure',
        'release_date' => '2017-03-03',
        'sales_numbers' => '22,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Minecraft',
        'category' => 'Sandbox',
        'release_date' => '2011-11-18',
        'sales_numbers' => '238,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Fortnite',
        'category' => 'Battle Royale',
        'release_date' => '2017-07-25',
        'sales_numbers' => '350,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Among Us',
        'category' => 'Social Deduction',
        'release_date' => '2018-06-15',
        'sales_numbers' => '500,000,000',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Red Dead Redemption 2',
        'category' => 'Action-Adventure',
        'release_date' => '2018-10-26',
        'sales_numbers' => '38,000,000',
        'github_username' => 'LilMaddy',
    ],
    [
        'title' => 'Horizon Zero Dawn',
        'category' => 'Action-Adventure',
        'release_date' => '2017-02-28',
        'sales_numbers' => '10,000,000',
        'github_username' => 'Legen32',
    ],
    [
        'title' => 'Grand Theft Auto V',
        'category' => 'action-adventure',
        'release_date' => '2013-09-17',
        'sales_numbers' => '140,000,000',
        'github_username' => 'tetawiah',
    ],
    [
        'title' => 'Tetris',
        'category' => 'Puzzle',
        'release_date' => '1984-06-06',
        'sales_numbers' => '170,000,000',
        'github_username' => 'tetawiah',
    ],
    [
        'title' => 'Call of Duty: Modern Warfare 2',
        'category' => 'First-person shooter',
        'release_date' => '2009-11-10',
        'sales_numbers' => '22,700,000',
        'github_username' => 'tetawiah',
    ],
    [
        'title' => 'Elden Ring',
        'category' => 'ARPG',
        'release_date' => '2022-02-25',
        'sales_numbers' => '20,500,000',
        'github_username' => 'harrydemorgan',
    ],
    [
        'title' => 'Counter-Strike: Global Offensive',
        'category' => 'First-person shooter',
        'release_date' => '2012-08-21',
        'sales_numbers' => '45,000,000+',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Beat Saber',
        'category' => 'Rhythm',
        'release_date' => '2018-05-01',
        'sales_numbers' => '6,000,000+',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Resident Evil 8: Village',
        'category' => 'Action-Adventure',
        'release_date' => '2021-05-07',
        'sales_numbers' => '8,000,000+',
        'github_username' => 'Omanshu209',
    ],
    [
        'title' => 'Mount & Blade II: Bannerlord',
        'category' => 'RPG',
        'release_date' => '2022-10-25',
        'sales_numbers' => '3,100,000+',
        'github_username' => 'AlandisAyupov',
    ],
    [
        'title' => 'Cyberpunk 2077',
        'category' => 'Action-Adventure',
        'release_date' => '2020-12-10',
        'sales_numbers' => '20,000,000+',
        'github_username' => 'Camarota-234',
    ],
    [
        'title' => 'God of War Ragnarök',
        'category' => 'Action-Adventure',
        'release_date' => '2022-11-09',
        'sales_numbers' => '11,000,000+',
        'github_username' => 'Camarota-234',
    ],
    [
        'title' => 'The Last of Us 2',
        'category' => 'Action-Adventure',
        'release_date' => '2020-19-06',
        'sales_numbers' => '10,000,000+',
        'github_username' => 'Camarota-234',
    ],
    [
        'title' => 'Phasmophobia',
        'category' => 'Adventure',
        'release_date' => '2020-9-18',
        'sales_numbers' => '5,000,000+',
        'github_username' => 'Omanshu209',
    ],
    [
        'title' => 'Infliction',
        'category' => 'Adventure',
        'release_date' => '2018-10-17',
        'sales_numbers' => '4,000,000+',
        'github_username' => 'Omanshu209',
    ],
    [
        'title' => 'MADiSON',
        'category' => 'Adventure',
        'release_date' => '2022-07-08',
        'sales_numbers' => '3,000,000+',
        'github_username' => 'Omanshu209',
    ],
    [
        'title' => 'Mount & Blade: Warband',
        'category' => 'Action RPG',
        'release_date' => '2010-03-30',
        'sales_numbers' => '6,000,000+',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Pummel Party',
        'category' => 'Party Game',
        'release_date' => '2018-09-20',
        'sales_numbers' => 'Over 1,000,000 on Steam',
        'github_username' => 'DoonOnthon',
    ],
    [
        'title' => 'Pummel Party',
        'category' => 'Party Game',
        'release_date' => '2018-09-20',
        'sales_numbers' => 'Over 1,000,000 on Steam',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'Mount & Blade: Warband',
        'category' => 'Action RPG',
        'release_date' => '2010-03-30',
        'sales_numbers' => '6,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'MADiSON',
        'category' => 'Adventure',
        'release_date' => '2022-07-08',
        'sales_numbers' => '3,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'Infliction',
        'category' => 'Adventure',
        'release_date' => '2018-10-17',
        'sales_numbers' => '4,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'Phasmophobia',
        'category' => 'Adventure',
        'release_date' => '2020-9-18',
        'sales_numbers' => '5,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'The Last of Us 2',
        'category' => 'Action-Adventure',
        'release_date' => '2020-19-06',
        'sales_numbers' => '10,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'God of War Ragnarök',
        'category' => 'Action-Adventure',
        'release_date' => '2022-11-09',
        'sales_numbers' => '11,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => 'Cyberpunk 2077',
        'category' => 'Action-Adventure',
        'release_date' => '2020-12-10',
        'sales_numbers' => '20,000,000+',
        'github_username' => 'IamSudhir-Kumar',
    ],
    [
        'title' => "Tom Clancy's Rainbow Six Siege",
        'category' => 'First-person shooter, Action, Strategy',
        'release_date' => '2015-12-01',
        'sales_numbers' => '36,000,000+',
        'github_username' => 'lucas-dantas10',
    ],
    [
        'title' => 'Rocket League',
        'category' => 'Electronic Sport Game, Action',
        'release_date' => '2015-07-07',
        'sales_numbers' => '10,000,000+',
        'github_username' => 'lucas-dantas10',
    ],
    [
        'title' => 'Hearthstone',
        'category' => 'Cards Game, Strategy',
        'release_date' => '2014-03-11',
        'sales_numbers' => '5,000,000+',
        'github_username' => 'lucas-dantas10',
    ],
    [
        'title' => 'New World',
        'category' => 'MMORPG, Action-Adventure',
        'release_date' => '2021-09-28',
        'sales_numbers' => '700,000+',
        'github_username' => 'lucas-dantas10',
    ],
    [
        'title' => 'Kingdom Hearts',
        'category' => 'Action RPG',
        'release_date' => '2002-03-28',
        'sales_numbers' => '100,000,000+',
        'github_username' => 'Emma-Jonna',
    ],
    [
        'title' => 'Untitled Goose Game',
        'category' => 'Puzzle, Stealth',
        'release_date' => '2019-09-20',
        'sales_numbers' => '5,000,000+',
        'github_username' => 'Emma-Jonna',
    ],
    [
        'title' => 'Ōkami',
        'category' => 'Action-Adventure',
        'release_date' => '2006-04-20',
        'sales_numbers' => '4,000,000+',
        'github_username' => 'Emma-Jonna',
    ],
    [
        'title' => 'Super Mario Odyssey',
        'category' => 'Platformer',
        'release_date' => '2017-10-27',
        'sales_numbers' => '20,230,000',
        'github_username' => 'adesh1998',
    ],
    [
    'title' => 'Lethal Company',
    'category' => 'First-person Shooter',
    'release_date' => '2023-06-15',
    'sales_numbers' => '12,500,000',
    'github_username' => 'DoonOnthon',
    ]

];
